# Generated by Django 3.2.4 on 2022-04-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readAt', models.DateTimeField(blank=True, default=None, null=True)),
                ('conversation', models.ForeignKey(db_column='conversationId', on_delete=django.db.models.deletion.CASCADE, related_name='readStatuses', related_query_name='readStatus', to='messenger_backend.conversation')),
                ('lastReadMessage', models.OneToOneField(blank=True, db_column='lastReadMessageId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger_backend.message')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='messenger_backend.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
